// Copyright (c) Meta Platforms, Inc. and affiliates.
//
// This source code is dual-licensed under either the MIT license found in the
// LICENSE-MIT file in the root directory of this source tree or the Apache
// License, Version 2.0 found in the LICENSE-APACHE file in the root directory
// of this source tree. You may select, at your option, one of the above-listed licenses.

//! An implementation of Oblivious SAM (OSAM).
//!
//! ⚠️ **Warning**: This implementation has not been audited. Use at your own risk!
//!
//! # Overview
//!
//! This crate implements an oblivious SAM protocol (OSAM).
//!
//! * `addr <- Alloc()` generates a fresh address that has not been allocated before.
//!
//! * `Write(addr, val)` writes the given value to its associated address.
//!   Addresses can be written to at most once.
//!   The given address must be produced by `Alloc()`.
//!
//! * `val <- Read(addr)` reads and returns the value associated with the given address.
//!   Addresses can only be read once.
//!   The given address must be produced by `Alloc()`.
//!   Reading an address that was allocated but not written is a valid operation.
//!
//! # Literature
//!
//! This crate implements Path OSAM as described for the
//! [OSAM Model](https://eprint.iacr.org/2024/1029.pdf). It is derived from
//! [Facebook's Path ORAM](https://github.com/facebook/oram) implementation.
//! Facebook's original oblivious client data structures are based on the
//! [Oblix paper](https://people.eecs.berkeley.edu/~raluca/oblix.pdf). See the
//! [Path ORAM retrospective paper](http://elaineshi.com/docs/pathoram-retro.pdf)
//! for a high-level introduction to Path ORAM.
//! Path OSAM deterministically evicts paths in a [reverse-lexicographic ordering](https://eprint.iacr.org/2013/239.pdf).
//!
//! # Design Specifications
//!
//! **Addresses**
//!
//! In this implementation of Path OSAM, addresses consist of a tuple `(identifier, position)`.
//! An identifier is uniquely given by an increasing counter to distinguish each block.
//! A position is the uniformly random leaf bucket a block is assigned to.
//!
//! **Correctness**
//!
//! For correctness, the client must respect the SAM rules:
//! * Valid addresses must be generated by `Alloc()`.
//! * Addresses can be read at most once.
//! * Addresses can be written at most once.
//!
//! There is no mechanism to enforce these rules.
//! It is up to the client to follow them correctly.
//!
//! **Eviction**
//!
//! In [Facebook's Path ORAM](https://github.com/facebook/oram), the path that was downloaded in a read
//! or write is always the path that is evicted.
//! We support two eviction strategies:
//! * [reverse-lexicographic eviction](https://eprint.iacr.org/2013/239.pdf), which deterministically
//!   and routinely evicts buckets.
//! * random eviction.
//!
//! When calling a function that evicts blocks to the server, use the boolean `ordered_evict` to toggle between
//! reverse-lexicographic eviction and random eviction.
//!
//! **Encryption**
//!
//! [Facebook's Path ORAM](https://github.com/facebook/oram) also assumes the ORAM is being run in the
//! secure enclave setting and does not perform encryption on-write.
//! We do not maintain this assumption and allow for toggling between encrypted and plaintext backends for Path OSAM+.
//! This can be toggled with the boolean `is_encrypted` when initializing a Path OSAM+.
//! The chosen encryption method is AES-GCM.
//!
//! **Miscellaneous**
//!
//! There are some miscellaneous functions that:
//! * locally writes a value to its associated address in the stash without evicting to the server.
//! * evict one path to the server without reading an address.
//! * return the number of times a certain operation was done.
//! * compute the variance and standard deviation on stash occupancy (number of real blocks in the stash).
//! * prints information of blocks in the server or in the stash (encrypted blocks are decrypted, displayed, and re-encrypted).
//!
//! # Example 1
//!
//! This example initialized an OSAM using Path OSAM.
//!
//! An OSAM can store arbitrary structs implementing `OsamBlock`.
//! We provide implementations of `OsamBlock` for `u8`, `u16`, `u32`, `u64`, `i8`, `i16`, `i32`, `i64`,
//! and `BlockValue<const B: BlockSize>`.
//!
//! ```
//! use osam::{
//!     path_osam::{DEFAULT_BLOCKS_PER_BUCKET, DEFAULT_STASH_OVERFLOW_SIZE},
//!     BlockSize, BlockValue, BucketSize, Identifier, Osam, OsamError, PathOsam, StashSize,
//! };
//! use rand::{rngs::OsRng, Rng};
//!
//! let mut rng = OsRng;
//! const BLOCK_SIZE: BlockSize = 64;
//! const DB_SIZE: Identifier = 64;
//! let is_encrypted = rng.gen_bool(0.5);
//!
//! const BUCKET_SIZE: BucketSize = DEFAULT_BLOCKS_PER_BUCKET;
//! const INITIAL_STASH_OVERFLOW_SIZE: StashSize = DEFAULT_STASH_OVERFLOW_SIZE;
//!
//! let mut osam = PathOsam::<
//!     BlockValue<BLOCK_SIZE>,
//!     DEFAULT_BLOCKS_PER_BUCKET,
//!     >::new(DB_SIZE, DEFAULT_STASH_OVERFLOW_SIZE, is_encrypted)?;
//! # Ok::<(), OsamError>(())
//! ```
//!
//! # Example 2
//!
//! The below example reads a database from memory into an OSAM, thus permitting secret-dependent accesses.
//!
//! ```
//! use osam::{
//!     DEFAULT_BLOCKS_PER_BUCKET, DEFAULT_STASH_OVERFLOW_SIZE,
//!     BlockSize, BlockValue, Identifier, Osam, OsamError, PathOsam, TreeIndex
//! };
//! use rand::{rngs::OsRng, Rng};
//!
//! const BLOCK_SIZE: BlockSize = 64;
//! const DB_SIZE: Identifier = 64;
//! const DATABASE: [[u8; BLOCK_SIZE as usize]; DB_SIZE as usize] =
//! [[0; BLOCK_SIZE as usize]; DB_SIZE as usize];
//! let mut rng = rand::rngs::OsRng;
//! let mut addresses: [(Identifier, TreeIndex); DB_SIZE as usize] =  
//! [(Identifier::MAX, 0); DB_SIZE as usize];
//! let is_encrypted = rng.gen_bool(0.5);
//!
//! // Initialize an OSAM to store 64 blocks of 64 bytes each.
//! let mut osam = PathOsam::<
//!     BlockValue<BLOCK_SIZE>,
//!     DEFAULT_BLOCKS_PER_BUCKET,
//!     >::new(DB_SIZE, DEFAULT_STASH_OVERFLOW_SIZE, is_encrypted)?;
//!
//! // Read a database (here, an array of byte arrays) into the OSAM.
//! for (i, bytes) in DATABASE.iter().enumerate() {
//!     let address = osam.alloc(&mut rng)?;
//!     addresses[i] = address;
//!     let identifier = address.0;
//!     let position = address.1;
//!     let ordered_evict = rng.gen_bool(0.5);
//!     let _ = osam.write(identifier, position, BlockValue::new(*bytes), ordered_evict, &mut rng)?;
//! }
//!
//! // Now you can safely make secret-dependent accesses to your database.
//! for (i, address) in addresses.iter().enumerate() {
//!     let address = addresses[i];
//!     let identifier = address.0;
//!     let position = address.1;
//!     let ordered_evict = rng.gen_bool(0.5);
//!     let bytes = osam.read(identifier, position, ordered_evict, &mut rng)?.unwrap();
//!     assert_eq!(bytes, BlockValue::new(DATABASE[i]));
//! }
//!
//! # Ok::<(), OsamError>(())
//! ```
//!
//! See [`PathOsam`] for an explanation of these parameters and their possible settings.

#![warn(clippy::cargo, clippy::doc_markdown, missing_docs, rustdoc::all)]

use bucket::LowLevelBytes;
use rand::{CryptoRng, Rng};
use std::num::TryFromIntError;
use subtle::ConditionallySelectable;
use thiserror::Error;

pub(crate) mod backend;
pub(crate) mod bucket;
pub mod path_osam;
pub(crate) mod stash;
#[cfg(test)]
mod test_utils;
pub(crate) mod utils;

pub use crate::{
    bucket::BlockValue,
    path_osam::{PathOsam, DEFAULT_BLOCKS_PER_BUCKET, DEFAULT_STASH_OVERFLOW_SIZE},
    utils::TreeIndex,
};

/// The numeric type used to specify the size of an OSAM block in bytes.
pub type BlockSize = usize;
/// The numeric type used to assign a unique identifier to a block.
pub type Identifier = u64;
/// The numeric type used to specify the size of an OSAM bucket in blocks.
pub type BucketSize = usize;
/// Numeric type used to represent the size of a Path OSAM stash in blocks.
pub type StashSize = u64;
/// Numeric type used to represent the evict counter in Path OSAM.
pub type CounterSize = u64;

/// A "trait alias" for OSAM blocks: the values read and written by an OSAM.
pub trait OsamBlock:
    Copy + Clone + std::fmt::Debug + Default + PartialEq + ConditionallySelectable + LowLevelBytes
{
}

impl OsamBlock for u8 {}
impl OsamBlock for u16 {}
impl OsamBlock for u32 {}
impl OsamBlock for u64 {}
impl OsamBlock for i8 {}
impl OsamBlock for i16 {}
impl OsamBlock for i32 {}
impl OsamBlock for i64 {}

/// A list of error types which are produced during OSAM protocol execution.
#[derive(Error, Debug)]
pub enum OsamError {
    /// Errors arising from conversions between integer types.
    #[error("Arithmetic error encountered.")]
    IntegerConversionError(#[from] TryFromIntError),
    /// Errors arising from invalid parameters or configuration.
    #[error("Invalid configuration. {parameter_name} cannot have value {parameter_value}.")]
    InvalidConfigurationError {
        /// The misconfigured parameter.
        parameter_name: String,
        /// Its invalid value.
        parameter_value: String,
    },
}

/// Represents an oblivious SAM (OSAM) mapping identifiers of type `Identifier`
/// and position of type `TreeIndex` to values of type `V: OsamBlock`.
pub trait Osam
where
    Self: Sized,
{
    /// The type of elements stored in the OSAM.
    type V: OsamBlock;

    /// Returns the capacity in blocks of this OSAM.
    fn block_capacity(&self) -> usize;

    /// Allocates a valid `Identifier` and random `TreeIndex` to be used for reading and writing.
    fn alloc<R: Rng + CryptoRng>(
        &mut self,
        rng: &mut R,
    ) -> Result<(Identifier, TreeIndex), OsamError>;

    /// Obliviously writes the value stored `identifier` and `position`. Evicts blocks to server.
    fn write<R: Rng + CryptoRng>(
        &mut self,
        identifier: Identifier,
        position: TreeIndex,
        value: Self::V,
        ordered_evict: bool,
        rng: &mut R,
    ) -> Result<(), OsamError>;

    /// Obliviously reads the value stored at `index`.
    fn read<R: Rng + CryptoRng>(
        &mut self,
        identifier: Identifier,
        position: TreeIndex,
        ordered_evict: bool,
        rng: &mut R,
    ) -> Result<Option<Self::V>, OsamError>;
}
